spring.application.name=demo

# Verbindung zur Render PostgreSQL Datenbank
spring.datasource.url=${URL}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatische Tabellenerstellung aktivieren
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
