spring.application.name=demo

# Verbindung zur Render PostgreSQL Datenbank
spring.datasource.url=jdbc:postgresql://dpg-d8n7bt3tqb8s73crlik0-a.frankfurt-postgres.render.com/webtech_db_qzp4?sslmode=require
spring.datasource.username=webtech_db_qzp4_user
spring.datasource.password=feRg8Zeqk7BRD6lmxLW2RhPbafmx8k9x
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Automatische Tabellenerstellung aktivieren
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
